// src/constants/index.ts

import { ConceptExplorerSettings, LanguageLabels, LanguageCode } from '../models';

// This file contains constants moved from main.ts

export const DEFAULT_PROMPT_TEMPLATE = `You are an idea generator. Your task is to generate related concepts based on the input provided.
Input Concept: "{concept}"
Context Path: "{fullPath}"
Desired Number of Concepts: {maxConcepts}
Response Language: {language}

Instructions:
1. Generate {maxConcepts} new, thought-provoking, or unexpected ideas related to the Input Concept.
2. Use the Context Path for inspiration, but do not repeat it.
3. Your entire response MUST be in {language}. Use full sentences in {language}.
4. Output the results ONLY as a valid JSON array of strings. Do not include any other text, formatting, or commentary.

Example JSON Output:
["관련 개념 1","관련 개념 2","관련 개념 3"]`;

export const DEFAULT_SETTINGS: ConceptExplorerSettings = {
	language: 'ko',
	llmService: 'ollama',
	model: 'llama3',
	maxDepth: 3,
	maxConcepts: 15,
	maxConceptsPerLevel: 10,
	diversity: 0.7,
	outputFolder: 'Concepts',
	openaiApiKey: '',
	claudeApiKey: '',
	geminiApiKey: '',
	ollamaUrl: 'http://localhost:11434',
	mcpUrl: 'http://localhost:3030',
	mcpType: 'stdio',
	mcpCommand: 'npx',
	mcpArgs: '-y @modelcontextprotocol/server-openai',
	aiApp: 'obsidian',
	customPrompt: '',
	enableFileInput: true,
	enableClipboardMonitoring: true,
	enableGraphView: true,
	enablePageOutline: true,
	autoSaveNotes: false,
	supportedFileTypes: ['pdf', 'docx', 'txt', 'md']
};

export const LANGUAGE_LABELS: Record<LanguageCode, LanguageLabels> = {
	'ko': {
		relatedConcepts: '관련 개념',
		conceptPath: '개념 경로',
		exploring: '개념 탐색 중',
		completed: '개념 웹 생성 완료!',
		depthLabel: '탐색 깊이',
		settings: '개념 탐색기 설정',
		language: '언어 / Language',
		languageDesc: '노트 및 UI에 사용할 언어를 선택하세요 / Select language for notes and UI',
		ollamaModel: 'Ollama 모델',
		ollamaModelDesc: '사용할 로컬 LLM 모델 선택',
		refreshModel: '모델 목록 새로고침',
		refreshModelDesc: 'Ollama 서버에서 사용 가능한 모델 목록을 다시 로드합니다',
		diversity: '다양성 바이어스',
		diversityDesc: '높을수록 더 다양한 개념을 찾습니다 (0.0-1.0)',
		maxDepth: '기본 최대 깊이',
		maxDepthDesc: '기본 탐색 깊이 설정',
		maxConcepts: '개념 수 제한',
		maxConceptsDesc: '각 개념당 생성할 최대 관련 개념 수',
		customPrompt: '사용자 정의 프롬프트 템플릿',
		customPromptDesc: `<p>개념 생성에 사용할 프롬프트 템플릿을 직접 정의할 수 있습니다.</p>\n<p>비워두면 기본 템플릿이 사용됩니다.</p>\n<p>다음 변수를 사용할 수 있습니다:</p>\n<ul>\n\t<li><code>{concept}</code> - 현재 개념</li>\n\t<li><code>{numConcepts}</code> - 생성할 개념 수</li>\n\t<li><code>{fullPath}</code> - 현재까지의 개념 경로</li>\n\t<li><code>{depth}</code> - 현재 깊이</li>\n</ul>\n<p>항상 JSON 형식의 배열로 반환되도록 프롬프트를 작성하세요.</p>`,
		resetPrompt: '기본값으로 초기화',
		outputFolder: '출력 폴더',
		outputFolderDesc: '생성된 노트를 저장할 폴더 경로',
		explorer: '개념 탐색기',
		rootConcept: '루트 개념',
		rootConceptDesc: '탐색을 시작할 개념을 입력하세요',
		depthSetting: '최대 깊이',
		depthSettingDesc: '개념 확장의 최대 깊이',
		start: '탐색 시작',
		cancel: '취소',
		cancelNotice: '개념 생성을 취소했습니다. 잠시만 기다려주세요...',
		cancelComplete: '취소 완료',
		selectText: '텍스트를 선택해주세요',
		errorExpanding: '개념 확장 중 오류가 발생했습니다',
		connectionError: '로컬 LLM 연결 오류. Ollama가 실행 중인지 확인해주세요.',
		enterRoot: '루트 개념을 입력해주세요',
		modelsFound: '개의 모델을 발견했습니다',
		noModels: '사용 가능한 모델이 없습니다. Ollama에서 모델을 먼저 다운로드하세요.',
		expandTitle: '개념 확장',
		selectedConcept: '선택된 개념',
		expandDepth: '확장 깊이',
		expandDepthDesc: '개념 확장의 깊이', 
		startExpand: '확장 시작',
		llmService: 'LLM 서비스',
		llmServiceDesc: '개념 생성에 사용할 LLM 서비스 선택',
		openaiApiKey: 'OpenAI API 키',
		openaiApiKeyDesc: 'OpenAI API 키를 입력하세요',
		claudeApiKey: 'Claude API 키',
		claudeApiKeyDesc: 'Anthropic Claude API 키를 입력하세요',
		geminiApiKey: 'Gemini API 키',
		geminiApiKeyDesc: 'Google Gemini API 키를 입력하세요',
		openaiModel: 'OpenAI 모델',
		openaiModelDesc: '사용할 OpenAI 모델 선택',
		claudeModel: 'Claude 모델',
		claudeModelDesc: '사용할 Claude 모델 선택',
		enableGraphView: '그래프 뷰 활성화',
		enableGraphViewDesc: '개념 간의 관계를 그래프 형태로 시각화',
		enablePageOutline: '페이지 개요 생성 활성화',
		enablePageOutlineDesc: '각 페이지에 대한 개요를 자동으로 생성',
		autoSaveNotes: '자동 노트 저장',
		autoSaveNotesDesc: '생성된 개념을 확인 없이 바로 노트로 저장합니다',
		save: '저장',
		saveLocation: '저장 위치',
		exploreDeeper: '더 깊이 탐색',
		close: '닫기',
		noResults: '결과가 없습니다',
		failed: '실패',
		generating: '생성 중...',
		mcpType: 'MCP 서버 유형',
		mcpTypeDesc: 'stdio(로컬 실행) 또는 SSE(원격 연결) 중 선택',
		stdioLocalServer: 'Stdio (로컬 서버)',
		sseRemoteServer: 'SSE (원격 서버)',
		model: 'MCP 모델',
		modelDesc: '사용할 MCP 모델 선택',
		custom: '사용자 정의',
		mcpCommand: 'MCP 명령어',
		mcpCommandDesc: 'stdio 서버를 실행할 명령어 (예: npx)',
		mcpArgs: 'MCP 인자',
		mcpArgsDesc: 'stdio 서버 인자',
		mcpHowToUse: 'MCP 사용 방법',
		mcpObsidianLimitation: '옵시디언은 브라우저 환경 제한으로 인해 직접 외부 명령을 실행할 수 없습니다.',
		mcpRunServerFirst: '먼저 터미널에서 MCP 서버를 실행하세요:',
		mcpCheckHttpEndpoint: 'MCP 서버가 로컬 HTTP 엔드포인트를 제공하는지 확인하세요.',
		mcpUrl: 'MCP 서버 URL',
		mcpUrlDesc: 'SSE 서버 URL (예: http://localhost:3030)',
		mcpSseHowToUse: 'MCP SSE 사용 방법',
		mcpSseEnterUrl: 'MCP SSE 서버에서 제공한 URL을 입력하세요.',
		mcpSseCheckRunning: '서버가 실행 중인지 확인하세요.',
		mcpSseClaudeConfig: 'Claude Desktop 통합을 위한 기본 설정:',
		mcpCopyCommand: '명령어 복사',
		mcpCommandCopied: 'MCP 명령어가 클립보드에 복사되었습니다.'
	},
	'en': {
		relatedConcepts: 'Related Concepts',
		conceptPath: 'Concept Path',
		exploring: 'Exploring concept',
		completed: 'Concept web generation completed!',
		depthLabel: 'Depth',
		settings: 'Concept Explorer Settings',
		language: 'Language / 언어',
		languageDesc: 'Select language for notes and UI / 노트 및 UI에 사용할 언어를 선택하세요',
		ollamaModel: 'Ollama Model',
		ollamaModelDesc: 'Select local LLM model to use',
		refreshModel: 'Refresh Model List',
		refreshModelDesc: 'Reload available models from Ollama server',
		diversity: 'Diversity Bias',
		diversityDesc: 'Higher values find more diverse concepts (0.0-1.0)',
		maxDepth: 'Default Max Depth',
		maxDepthDesc: 'Set default exploration depth',
		maxConcepts: 'Concepts Limit',
		maxConceptsDesc: 'Maximum number of related concepts to generate per concept',
		customPrompt: 'Custom Prompt Template',
		customPromptDesc: `<p>Define your own prompt template for concept generation.</p>\n<p>Leave empty to use the default template.</p>\n<p>You can use the following variables:</p>\n<ul>\n\t<li><code>{concept}</code> - current concept</li>\n\t<li><code>{numConcepts}</code> - number of concepts to generate</li>\n\t<li><code>{fullPath}</code> - full concept path so far</li>\n\t<li><code>{depth}</code> - current depth</li>\n</ul>\n<p>Make sure your prompt returns a JSON array of strings.</p>`,
		resetPrompt: 'Reset to Default',
		outputFolder: 'Output Folder',
		outputFolderDesc: 'Path for saving generated notes',
		explorer: 'Concept Explorer',
		rootConcept: 'Root Concept',
		rootConceptDesc: 'Enter a concept to start exploring',
		depthSetting: 'Maximum Depth',
		depthSettingDesc: 'Maximum depth of concept expansion',
		start: 'Start Exploration',
		cancel: 'Cancel',
		cancelNotice: 'Concept generation canceled. Please wait...',
		cancelComplete: 'Cancellation complete',
		selectText: 'Please select some text',
		errorExpanding: 'Error occurred while expanding concepts',
		connectionError: 'Local LLM connection error. Please make sure Ollama is running.',
		enterRoot: 'Please enter a root concept',
		modelsFound: 'model(s) found',
		noModels: 'No available models. Please download models in Ollama first.',
		expandTitle: 'Expand Concept',
		selectedConcept: 'Selected concept',
		expandDepth: 'Expansion Depth',
		expandDepthDesc: 'Depth of concept expansion',
		startExpand: 'Start Expansion',
		llmService: 'LLM Service',
		llmServiceDesc: 'Select the LLM service to use for concept generation',
		openaiApiKey: 'OpenAI API Key',
		openaiApiKeyDesc: 'Enter your OpenAI API key',
		claudeApiKey: 'Claude API Key',
		claudeApiKeyDesc: 'Enter your Anthropic Claude API key',
		geminiApiKey: 'Gemini API Key',
		geminiApiKeyDesc: 'Enter your Google Gemini API key',
		openaiModel: 'OpenAI Model',
		openaiModelDesc: 'Select OpenAI model to use',
		claudeModel: 'Claude Model',
		claudeModelDesc: 'Select Claude model to use',
		enableGraphView: 'Enable Graph View',
		enableGraphViewDesc: 'Visualize relationships between concepts as a graph',
		enablePageOutline: 'Enable Page Outline',
		enablePageOutlineDesc: 'Automatically generate outline for each page',
		autoSaveNotes: 'Auto Save Notes',
		autoSaveNotesDesc: 'Save generated concepts directly to notes without confirmation',
		save: 'Save',
		saveLocation: 'Save Location',
		exploreDeeper: 'Explore Deeper',
		close: 'Close',
		noResults: 'No Results',
		failed: 'Failed',
		generating: 'Generating...',
		mcpType: 'MCP Server Type',
		mcpTypeDesc: 'Choose between stdio (local execution) or SSE (remote connection)',
		stdioLocalServer: 'Stdio (Local Server)',
		sseRemoteServer: 'SSE (Remote Server)',
		model: 'MCP Model',
		modelDesc: 'Select MCP model to use',
		custom: 'Custom',
		mcpCommand: 'MCP Command',
		mcpCommandDesc: 'Command to execute stdio server (e.g. npx)',
		mcpArgs: 'MCP Arguments',
		mcpArgsDesc: 'Arguments for stdio server',
		mcpHowToUse: 'How to Use MCP',
		mcpObsidianLimitation: 'Obsidian cannot execute external commands directly due to browser environment restrictions.',
		mcpRunServerFirst: 'Run the MCP server in your terminal first:',
		mcpCheckHttpEndpoint: 'Make sure the MCP server provides a local HTTP endpoint.',
		mcpUrl: 'MCP Server URL',
		mcpUrlDesc: 'URL for SSE server (e.g. http://localhost:3030)',
		mcpSseHowToUse: 'How to Use MCP SSE',
		mcpSseEnterUrl: 'Enter the URL provided by the MCP SSE server.',
		mcpSseCheckRunning: 'Make sure the server is running.',
		mcpSseClaudeConfig: 'For Claude Desktop integration, check the default configuration:',
		mcpCopyCommand: 'Copy Command',
		mcpCommandCopied: 'MCP command copied to clipboard.'
	},
}; 